/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paparon;

import config.dbConnect;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setResizable(false);
        

    }
    Set<String> existingUsernames = new HashSet<>();
    Set<String> existingEmails = new HashSet<>();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        use = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        lan = new javax.swing.JTextField();
        can = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        passwe = new javax.swing.JPasswordField();
        ps = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        emai = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        lasn = new javax.swing.JLabel();
        firn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        occ1 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        occ = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useActionPerformed(evt);
            }
        });
        getContentPane().add(use, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 180, 30));

        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });
        getContentPane().add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 180, 30));

        lan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanActionPerformed(evt);
            }
        });
        getContentPane().add(lan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, 30));

        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        getContentPane().add(can, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 180, 30));

        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 180, 30));

        passwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passweActionPerformed(evt);
            }
        });
        getContentPane().add(passwe, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, 30));

        ps.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ps.setForeground(new java.awt.Color(0, 255, 255));
        ps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ps.setText("Password:");
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, -1));

        un.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        un.setForeground(new java.awt.Color(0, 255, 255));
        un.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        un.setText("Username:");
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, 20));

        emai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emai.setForeground(new java.awt.Color(0, 255, 255));
        emai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emai.setText("Email:");
        getContentPane().add(emai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 100, -1));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cn.setForeground(new java.awt.Color(0, 255, 255));
        cn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cn.setText("Contact Number:");
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, 20));

        lasn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lasn.setForeground(new java.awt.Color(0, 255, 255));
        lasn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lasn.setText("Last Name: ");
        getContentPane().add(lasn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, -1));

        firn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firn.setForeground(new java.awt.Color(0, 255, 255));
        firn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firn.setText("First Name:");
        getContentPane().add(firn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 100, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Here!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 280, 40));

        occ1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        occ1.setForeground(new java.awt.Color(0, 255, 255));
        occ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occ1.setText("Occupation:");
        getContentPane().add(occ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, -1));

        Register.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 90, 30));

        Clear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 90, 30));

        Back.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 90, 30));

        occ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Manager", "Cashier"}));
        occ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occActionPerformed(evt);
            }
        });
        getContentPane().add(occ, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nm.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 620, 520));

        setBounds(0, 0, 637, 419);
    }// </editor-fold>//GEN-END:initComponents

    private void useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useActionPerformed

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finActionPerformed

    private void lanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void passweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passweActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        
        
        
         

    

 
    if (fin.getText().isEmpty() || lan.getText().isEmpty() ||  can.getText().isEmpty() ||  em.getText().isEmpty() ||  use.getText().isEmpty() ||  passwe.getPassword().length == 0 ) {
        JOptionPane.showMessageDialog(null, "All Fields Are Required");
     


    } 
    else if (fin.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "First Name is required");
    fin.setText("");
    }
     else if (lan.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "First Name is required");
    lan.setText("");
     }
     else if (can.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Contact Number is required");
    can.setText("");
} else {
    String input = can.getText();
    if (!input.matches("[0-9]{11}")) {  
        JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits only)");
        can.setText("");
    }

    
    else if (em.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Email is required");
    em.setText(""); 
      
     
}
      else {
            String email = em.getText();
            
           
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            Pattern pattern = Pattern.compile(emailRegex);
            Matcher matcher = pattern.matcher(email);

            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid email with @yahoo.com or @gmail.com");
                em.setText("");
            }
      
              
   else if (use.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Username is required");
    use.setText(""); 
} 
else if (passwe.getPassword().length == 0) {
    
    JOptionPane.showMessageDialog(null, "Password is required");
    passwe.setText(""); 
} 
else if (passwe.getPassword().length < 8) {
    JOptionPane.showMessageDialog(null, "Password should have at least 8 characters");
    passwe.setText("");
} 


   

else {
     dbConnect dbc = new dbConnect();
       String checkUsernameQuery = "SELECT COUNT(*) FROM tbl_user WHERE u_user = '" + use.getText() + "'";
                int usernameCount = dbc.executeQueryForCount(checkUsernameQuery);
                if (usernameCount > 0) {
                    JOptionPane.showMessageDialog(null, "Username is already taken");
                    return;
                }

                
                String checkEmailQuery = "SELECT COUNT(*) FROM tbl_user WHERE u_em = '" + em.getText() + "'";
                int emailCount = dbc.executeQueryForCount(checkEmailQuery);
                if (emailCount > 0) {
                    JOptionPane.showMessageDialog(null, "Email is already registered");
                    return; 
                }

              
                String insertQuery = "INSERT INTO tbl_user(u_fname, u_lname, u_occ, u_cn, u_em, u_user, u_pass, u_status)"
                        + "VALUES('"+fin.getText()+"', '"+lan.getText()+"', '"+occ.getSelectedItem()+"', '"+can.getText()+"', '"+em.getText()+"', '"+use.getText()+"', '"+passwe.getText()+"', 'Pending')";
                
                if (dbc.insertData(insertQuery) == 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully");
                }
            
           
    
    new LoginPage().setVisible(true);
    this.setVisible(false);
    this.dispose();
}
    }//GEN-LAST:event_RegisterActionPerformed
     }
    }
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        
    use.setText("");  
    fin.setText(""); 
    lan.setText("");  
    can.setText("");  
    em.setText("");  
    passwe.setText(""); 

    }//GEN-LAST:event_ClearActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void occActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_occActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Register;
    private javax.swing.JTextField can;
    private javax.swing.JLabel cn;
    private javax.swing.JTextField em;
    private javax.swing.JLabel emai;
    private javax.swing.JTextField fin;
    private javax.swing.JLabel firn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField lan;
    private javax.swing.JLabel lasn;
    private javax.swing.JComboBox<String> occ;
    private javax.swing.JLabel occ1;
    private javax.swing.JPasswordField passwe;
    private javax.swing.JLabel ps;
    private javax.swing.JLabel un;
    private javax.swing.JTextField use;
    // End of variables declaration//GEN-END:variables
}
