/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import javax.swing.JOptionPane;
import config.dbConnect;
import java.awt.print.PrinterException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import paparon.LoginPage;

/**
 *
 * @author PC
 */
public class FoodMenu extends javax.swing.JFrame {

    
    double total=0.0;
    private int x =0;
    
    /**
     * 
     * Creates new form FoodMenu
     */
    public FoodMenu() {
        initComponents();
        setTime();
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        
    }
    
    public boolean qtyisZero(int qty){
        
    if(qty==0){
     JOptionPane.showMessageDialog(null, "Please increase value");   
     return false;
    }
    return true;
    }
    
    public void Reset(){
    jSpinner1.setValue(0);
    jSpinner2.setValue(0);
    jSpinner3.setValue(0);
    jSpinner4.setValue(0);
    jSpinner5.setValue(0);
    jSpinner6.setValue(0);
    jSpinner7.setValue(0);
    jSpinner8.setValue(0);
    jTextArea1.setText("");
    jCheckBox1.setSelected(false);
    jCheckBox2 .setSelected(false);
    jCheckBox3.setSelected(false);
    jCheckBox4.setSelected(false);
    jCheckBox5.setSelected(false);
    jCheckBox6.setSelected(false);
    jCheckBox7.setSelected(false);
    jCheckBox8.setSelected(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Burger = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        Fries = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        Burgersteak = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        Chicken = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        Icecream = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        Hotdog = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        Taco = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        Pizza = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jLabel50 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Time = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        total1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Receipt = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Burger1 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel56 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        Fries1 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel62 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        Burgersteak1 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel68 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        Chicken1 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jLabel74 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        Hotdog1 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jSpinner13 = new javax.swing.JSpinner();
        jLabel80 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        Pizza1 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jSpinner14 = new javax.swing.JSpinner();
        jLabel86 = new javax.swing.JLabel();
        jCheckBox14 = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        sprite = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jSpinner16 = new javax.swing.JSpinner();
        jLabel98 = new javax.swing.JLabel();
        jCheckBox16 = new javax.swing.JCheckBox();
        jPanel21 = new javax.swing.JPanel();
        icedcoffee = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jSpinner19 = new javax.swing.JSpinner();
        jLabel116 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        coke = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jSpinner15 = new javax.swing.JSpinner();
        jLabel92 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        water = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jSpinner20 = new javax.swing.JSpinner();
        jLabel122 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        smoothie = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jSpinner18 = new javax.swing.JSpinner();
        jLabel110 = new javax.swing.JLabel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        icedtea = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jSpinner17 = new javax.swing.JSpinner();
        jLabel104 = new javax.swing.JLabel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Burger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/030-burger.png"))); // NOI18N
        jPanel2.add(Burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Price:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Quantity:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Burger");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("25.0");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Purchase:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/031-fried-potatoes.png"))); // NOI18N
        jPanel3.add(Fries, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Name:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Price:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Quantity:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Fries");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("20.0");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel3.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Purchase:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 210));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Burgersteak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Burgersteak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/037-grill.png"))); // NOI18N
        jPanel4.add(Burgersteak, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Name:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Price:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Quantity:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Burger Steak");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 102, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("35.0");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel4.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Purchase:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 210));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chicken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/032-fried-chicken.png"))); // NOI18N
        jPanel5.add(Chicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Name:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Price:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Quantity:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Chicken");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("35.0");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel5.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Purchase:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });
        jPanel5.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 210));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icecream.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icecream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/035-ice-cream.png"))); // NOI18N
        jPanel6.add(Icecream, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 160, 82));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Name:");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Price:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Quantity:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("Ice Cream");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("20.0");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel6.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("Purchase:");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jPanel6.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 160, 210));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hotdog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hotdog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/033-hot-dog.png"))); // NOI18N
        jPanel7.add(Hotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel33.setText("Name:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("Price:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel35.setText("Quantity:");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel36.setText("Hotdog");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel37.setText("40.0");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel7.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel38.setText("Purchase:");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });
        jPanel7.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, 210));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Taco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Taco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/034-taco.png"))); // NOI18N
        jPanel8.add(Taco, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 160, 82));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel39.setText("Name:");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel40.setText("Price:");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel41.setText("Quantity:");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel42.setText("Taco");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel43.setText("30.0");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel8.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel44.setText("Purchase:");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
        });
        jPanel8.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, 210));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/036-pizza.png"))); // NOI18N
        jPanel9.add(Pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 160, 82));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel45.setText("Name:");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel46.setText("Price:");
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel47.setText("Quantity:");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel48.setText("Pizza");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel49.setText("50.0");
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel9.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel50.setText("Purchase:");
        jPanel9.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox8MouseClicked(evt);
            }
        });
        jPanel9.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 160, 210));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Food Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 5, 670, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 540));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 490));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 330, 590));

        Time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 120, 40));
        getContentPane().add(Date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 160, 40));

        total1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total1.setText("Total");
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 670, 130, 40));

        Reset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 130, 40));

        Receipt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Receipt.setText("Receipt");
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });
        getContentPane().add(Receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 130, 40));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(Burger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel51.setText("Name:");
        jPanel11.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel52.setText("Price:");
        jPanel11.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel53.setText("Quantity:");
        jPanel11.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel54.setText("Coke");
        jPanel11.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel55.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel55.setText("20.00");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel11.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel56.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel56.setText("Purchase:");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel11.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 210));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(Fries1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel57.setText("Name:");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel58.setText("Price:");
        jPanel12.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel59.setText("Quantity:");
        jPanel12.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel60.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel60.setText("Sprite");
        jPanel12.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel61.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel61.setText("20.00");
        jPanel12.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel12.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel62.setText("Purchase:");
        jPanel12.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel12.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 210));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(Burgersteak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel63.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel63.setText("Name:");
        jPanel13.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel64.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel64.setText("Price:");
        jPanel13.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel65.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel65.setText("Quantity:");
        jPanel13.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel66.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel66.setText("Iced Tea");
        jPanel13.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel67.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel67.setText("20.00");
        jPanel13.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel13.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel68.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel68.setText("Purchase:");
        jPanel13.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel13.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 210));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(Chicken1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel69.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel69.setText("Name:");
        jPanel14.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel70.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel70.setText("Price:");
        jPanel14.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel71.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel71.setText("Quantity:");
        jPanel14.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel72.setText("Smoothie");
        jPanel14.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel73.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel73.setText("30.00");
        jPanel14.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel14.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel74.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel74.setText("Purchase:");
        jPanel14.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel14.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, 210));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(Hotdog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel75.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel75.setText("Name:");
        jPanel15.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel76.setText("Price:");
        jPanel15.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel77.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel77.setText("Quantity:");
        jPanel15.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel78.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel78.setText("Iced Coffee");
        jPanel15.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, 20));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel79.setText("40.00");
        jPanel15.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel15.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel80.setText("Purchase:");
        jPanel15.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel15.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, 210));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(Pizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel81.setText("Name:");
        jPanel16.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel82.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel82.setText("Price:");
        jPanel16.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel83.setText("Quantity:");
        jPanel16.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel84.setText("Water");
        jPanel16.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel85.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel85.setText("15.00");
        jPanel16.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel16.add(jSpinner14, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel86.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel86.setText("Purchase:");
        jPanel16.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));
        jPanel16.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 160, 210));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sprite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/039-soda.png"))); // NOI18N
        jPanel18.add(sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel93.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel93.setText("Name:");
        jPanel18.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel94.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel94.setText("Price:");
        jPanel18.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel95.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel95.setText("Quantity:");
        jPanel18.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel96.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel96.setText("Sprite");
        jPanel18.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel97.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel97.setText("20.0");
        jPanel18.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner16.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel18.add(jSpinner16, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel98.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel98.setText("Purchase:");
        jPanel18.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox16MouseClicked(evt);
            }
        });
        jPanel18.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, -1, 210));

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icedcoffee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icedcoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/042-iced-coffee.png"))); // NOI18N
        jPanel21.add(icedcoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel111.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel111.setText("Name:");
        jPanel21.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel112.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel112.setText("Price:");
        jPanel21.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel113.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel113.setText("Quantity:");
        jPanel21.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel114.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel114.setText("Iced Coffee");
        jPanel21.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, -1));

        jLabel115.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel115.setText("40.0");
        jPanel21.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner19.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel21.add(jSpinner19, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel116.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel116.setText("Purchase:");
        jPanel21.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox19MouseClicked(evt);
            }
        });
        jPanel21.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 820, 150, 210));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/038-coke.png"))); // NOI18N
        jPanel17.add(coke, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 150, 82));

        jLabel87.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel87.setText("Name:");
        jPanel17.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel88.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel88.setText("Price:");
        jPanel17.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel89.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel89.setText("Quantity:");
        jPanel17.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel90.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel90.setText("Coke");
        jPanel17.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel91.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel91.setText("20.0");
        jPanel17.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner15.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel17.add(jSpinner15, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel92.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel92.setText("Purchase:");
        jPanel17.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox15MouseClicked(evt);
            }
        });
        jPanel17.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 150, 210));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        water.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/043-water.png"))); // NOI18N
        jPanel22.add(water, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 160, 82));

        jLabel117.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel117.setText("Name:");
        jPanel22.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel118.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel118.setText("Price:");
        jPanel22.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel119.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel119.setText("Quantity:");
        jPanel22.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel120.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel120.setText("Water");
        jPanel22.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 59, -1));

        jLabel121.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel121.setText("15.0");
        jPanel22.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner20.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel22.add(jSpinner20, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel122.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel122.setText("Purchase:");
        jPanel22.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox20MouseClicked(evt);
            }
        });
        jPanel22.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 820, 160, 210));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        smoothie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smoothie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/041-smoothie.png"))); // NOI18N
        jPanel20.add(smoothie, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel105.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel105.setText("Name:");
        jPanel20.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel106.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel106.setText("Price:");
        jPanel20.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel107.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel107.setText("Quantity:");
        jPanel20.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel108.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel108.setText("Smoothie");
        jPanel20.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel109.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel109.setText("30.0");
        jPanel20.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner18.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel20.add(jSpinner18, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel110.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel110.setText("Purchase:");
        jPanel20.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox18MouseClicked(evt);
            }
        });
        jPanel20.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, -1, 210));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icedtea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icedtea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/040-lemon-tea.png"))); // NOI18N
        jPanel19.add(icedtea, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 157, 82));

        jLabel99.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel99.setText("Name:");
        jPanel19.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));

        jLabel100.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel100.setText("Price:");
        jPanel19.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel101.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel101.setText("Quantity:");
        jPanel19.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jLabel102.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel102.setText("Iced Tea");
        jPanel19.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 102, -1, -1));

        jLabel103.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel103.setText("20.0");
        jPanel19.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 123, -1, -1));

        jSpinner17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinner17.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel19.add(jSpinner17, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 144, 46, -1));

        jLabel104.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel104.setText("Purchase:");
        jPanel19.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jCheckBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox17MouseClicked(evt);
            }
        });
        jPanel19.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 175, -1, -1));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, 210));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Drinks Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 650, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_ResetActionPerformed

     public void fms(){
      jTextArea1.setText("**************Food Management System**************\n"
                + "Time:" + Time.getText() + " Date :" + Date1.getText() + "\n"
                + "**********************************************************\n"
                + "Item Name\t\t\tPrice\n"); 
    }
    
    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        int qty = Integer.parseInt(jSpinner1.getValue().toString());
        if(qtyisZero(qty) && jCheckBox1.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*25.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel6.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox1.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner2.getValue().toString());
        if(qtyisZero(qty) && jCheckBox2.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*20.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel12.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox2.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
         int qty = Integer.parseInt(jSpinner3.getValue().toString());
        if(qtyisZero(qty) && jCheckBox3.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*35.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel18.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox3.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner4.getValue().toString());
        if(qtyisZero(qty) && jCheckBox4.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*35.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel24.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox4.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner6.getValue().toString());
        if(qtyisZero(qty) && jCheckBox6.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*40.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel36.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox6.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner7.getValue().toString());
        if(qtyisZero(qty) && jCheckBox7.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*30.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel42.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox7.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox7MouseClicked

    private void jCheckBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox8MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner8.getValue().toString());
        if(qtyisZero(qty) && jCheckBox8.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*50.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel48.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox8.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox8MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner5.getValue().toString());
        if(qtyisZero(qty) && jCheckBox5.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*20.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel30.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox5.setSelected(false);
            
            
        }
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
         total = 0.0;

    if (jCheckBox1.isSelected() && (int) jSpinner1.getValue() > 0) {
        total += (int) jSpinner1.getValue() * 25.0;
    }
    if (jCheckBox2.isSelected() && (int) jSpinner2.getValue() > 0) {
        total += (int) jSpinner2.getValue() * 20.0;
    }
    if (jCheckBox3.isSelected() && (int) jSpinner3.getValue() > 0) {
        total += (int) jSpinner3.getValue() * 35.0;
    }
    if (jCheckBox4.isSelected() && (int) jSpinner4.getValue() > 0) {
        total += (int) jSpinner4.getValue() * 20.0;
    }
    if (jCheckBox6.isSelected() && (int) jSpinner6.getValue() > 0) {
        total += (int) jSpinner6.getValue() * 40.0;
    }
    if (jCheckBox7.isSelected() && (int) jSpinner7.getValue() > 0) {
        total += (int) jSpinner7.getValue() * 30.0;
    }
    if (jCheckBox8.isSelected() && (int) jSpinner8.getValue() > 0) {
        total += (int) jSpinner8.getValue() * 50.0;
    }
    if (jCheckBox5.isSelected() && (int) jSpinner5.getValue() > 0) {
        total += (int) jSpinner5.getValue() * 20.0;
    }
     if (jCheckBox15.isSelected() && (int) jSpinner15.getValue() > 0) {
        total += (int) jSpinner1.getValue() * 20.0;
    }
    if (jCheckBox16.isSelected() && (int) jSpinner16.getValue() > 0) {
        total += (int) jSpinner2.getValue() * 20.0;
    }
    if (jCheckBox17.isSelected() && (int) jSpinner17.getValue() > 0) {
        total += (int) jSpinner3.getValue() * 20.0;
    }
    if (jCheckBox18.isSelected() && (int) jSpinner18.getValue() > 0) {
        total += (int) jSpinner4.getValue() * 20.0;
    }
    if (jCheckBox19.isSelected() && (int) jSpinner19.getValue() > 0) {
        total += (int) jSpinner6.getValue() * 40.0;
    }
    if (jCheckBox20.isSelected() && (int) jSpinner20.getValue() > 0) {
        total += (int) jSpinner7.getValue() * 15.0;
    }

    jTextArea1.append("-------------------------------------------------------------------\n");
    jTextArea1.append("Total:\t\t\t" + String.format("%.1f", total) + "\n");
   
      dbConnect dbc = new dbConnect();
Connection con = null;
PreparedStatement pstmtOrder = null; 
PreparedStatement pstmtReceipt = null; 


        String insertOrderQuery = "INSERT INTO tbl_orders(burger_qty, fries_qty, burgersteak_qty, chicken_qty, hotdog_qty, taco_qty, pizza_qty, icecream_qty, coke_qty, sprite_qty, icedtea_qty, smoothie_qty, icedcoffee_qty, water_qty)"
                + " VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        String insertReceiptQuery = "INSERT INTO tbl_receipt( u_fid, total_amount)"
                           + " VALUES(?, ?)"; 
        
       
        try {
             con = dbc.getConnection();
             con.setAutoCommit(false);
            pstmtOrder = con.prepareStatement(insertOrderQuery, Statement.RETURN_GENERATED_KEYS);
            pstmtOrder.setInt(1, jCheckBox1.isSelected() ? Integer.parseInt(jSpinner1.getValue().toString()) : 0);
            pstmtOrder.setInt(2, jCheckBox2.isSelected() ? Integer.parseInt(jSpinner2.getValue().toString()) : 0);
            pstmtOrder.setInt(3, jCheckBox3.isSelected() ? Integer.parseInt(jSpinner3.getValue().toString()) : 0);
            pstmtOrder.setInt(4, jCheckBox4.isSelected() ? Integer.parseInt(jSpinner4.getValue().toString()) : 0);
            pstmtOrder.setInt(5, jCheckBox6.isSelected() ? Integer.parseInt(jSpinner6.getValue().toString()) : 0);
            pstmtOrder.setInt(6, jCheckBox7.isSelected() ? Integer.parseInt(jSpinner7.getValue().toString()) : 0);
            pstmtOrder.setInt(7, jCheckBox8.isSelected() ? Integer.parseInt(jSpinner8.getValue().toString()) : 0);
            pstmtOrder.setInt(8, jCheckBox5.isSelected() ? Integer.parseInt(jSpinner5.getValue().toString()) : 0);
            pstmtOrder.setInt(9, jCheckBox15.isSelected() ? Integer.parseInt(jSpinner2.getValue().toString()) : 0);
            pstmtOrder.setInt(10, jCheckBox16.isSelected() ? Integer.parseInt(jSpinner3.getValue().toString()) : 0);
            pstmtOrder.setInt(11, jCheckBox17.isSelected() ? Integer.parseInt(jSpinner4.getValue().toString()) : 0);
            pstmtOrder.setInt(12, jCheckBox18.isSelected() ? Integer.parseInt(jSpinner6.getValue().toString()) : 0);
            pstmtOrder.setInt(13, jCheckBox19.isSelected() ? Integer.parseInt(jSpinner7.getValue().toString()) : 0);
            pstmtOrder.setInt(14, jCheckBox20.isSelected() ? Integer.parseInt(jSpinner8.getValue().toString()) : 0);
            

           int rowsInsertedOrder = pstmtOrder.executeUpdate();
    int u_fid = -1; // 

    if (rowsInsertedOrder > 0) {
        ResultSet generatedKeys = pstmtOrder.getGeneratedKeys();
        if (generatedKeys.next()) {
            u_fid = generatedKeys.getInt(1); 
        }

        
        pstmtReceipt = con.prepareStatement(insertReceiptQuery);
        pstmtReceipt.setInt(1, u_fid);
        pstmtReceipt.setDouble(2, total);
       

        int rowsInsertedReceipt = pstmtReceipt.executeUpdate();

        if (rowsInsertedReceipt > 0) {
            con.commit(); 
            JOptionPane.showMessageDialog(this, "Order and receipt details saved to database!");
        } else {
            con.rollback(); 
            JOptionPane.showMessageDialog(this, "Failed to save receipt details.");
        }
    } else {
        con.rollback(); 
        JOptionPane.showMessageDialog(this, "Failed to save order details.");
    }

} catch (SQLException ex) {
    try {
        if (con != null) con.rollback();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    Logger.getLogger(FoodMenu.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
} finally {
    try {
        if (pstmtReceipt != null) pstmtReceipt.close();
        if (pstmtOrder != null) pstmtOrder.close();
        if (con != null) dbc.closeConnection(con);
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_total1ActionPerformed

    
    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
        // TODO add your handling code here:
        if(total != 0){
            
            try {
                jTextArea1.print();
            } catch (PrinterException ex) {
                Logger.getLogger(FoodMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "You haven't purchased any product");
        }
    }//GEN-LAST:event_ReceiptActionPerformed

    private void jCheckBox15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox15MouseClicked
        // TODO add your handling code here:
        int qty = Integer.parseInt(jSpinner15.getValue().toString());
        if(qtyisZero(qty) && jCheckBox15.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*20.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel90.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox15.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox15MouseClicked

    private void jCheckBox16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox16MouseClicked
        // TODO add your handling code here:
          int qty = Integer.parseInt(jSpinner16.getValue().toString());
        if(qtyisZero(qty) && jCheckBox16.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*20.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel96.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox16.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox16MouseClicked

    private void jCheckBox17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox17MouseClicked
        // TODO add your handling code here:
         int qty = Integer.parseInt(jSpinner17.getValue().toString());
        if(qtyisZero(qty) && jCheckBox17.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*20.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel102.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox17.setSelected(false);
        }

        
    }//GEN-LAST:event_jCheckBox17MouseClicked

    private void jCheckBox18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox18MouseClicked
        // TODO add your handling code here:
        int qty = Integer.parseInt(jSpinner18.getValue().toString());
        if(qtyisZero(qty) && jCheckBox18.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*30.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel108.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox18.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox18MouseClicked

    private void jCheckBox19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox19MouseClicked
        // TODO add your handling code here:
         int qty = Integer.parseInt(jSpinner19.getValue().toString());
        if(qtyisZero(qty) && jCheckBox19.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*40.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel114.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox19.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox19MouseClicked

    private void jCheckBox20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox20MouseClicked
        // TODO add your handling code here:
        int qty = Integer.parseInt(jSpinner20.getValue().toString());
        if(qtyisZero(qty) && jCheckBox20.isSelected() ){
            x++;
            if(x==1){
            fms();
            }
            double price = qty*15.0;
            jTextArea1.setText(jTextArea1.getText()+x+". "+jLabel120.getText()+"\t\t\t"+price+"\n");
        }else{
            jCheckBox20.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox20MouseClicked

    
   
    
    public void setTime(){
        new Thread(new Runnable(){
          @Override
          public void run(){
          while(true){
             
              try {
                  Thread.sleep(1000);
              } catch (InterruptedException ex) {
                  Logger.getLogger(FoodMenu.class.getName()).log(Level.SEVERE, null, ex);
              }
              Date date = new Date();
              SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
              SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
              String time = tf.format(date);
              Time.setText(time.split(" ")[0]+" "+time.split(" ")[1]);
              Date1.setText(df.format (date));
          }
          }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Burger;
    private javax.swing.JLabel Burger1;
    private javax.swing.JLabel Burgersteak;
    private javax.swing.JLabel Burgersteak1;
    private javax.swing.JLabel Chicken;
    private javax.swing.JLabel Chicken1;
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel Fries;
    private javax.swing.JLabel Fries1;
    private javax.swing.JLabel Hotdog;
    private javax.swing.JLabel Hotdog1;
    private javax.swing.JLabel Icecream;
    private javax.swing.JLabel Pizza;
    private javax.swing.JLabel Pizza1;
    private javax.swing.JButton Receipt;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Taco;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel coke;
    private javax.swing.JLabel icedcoffee;
    private javax.swing.JLabel icedtea;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner19;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner20;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel smoothie;
    private javax.swing.JLabel sprite;
    private javax.swing.JButton total1;
    private javax.swing.JLabel water;
    // End of variables declaration//GEN-END:variables
}
