/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import config.Session;
import config.dbConnect;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import manager.ManageUsers;

/**
 *
 * @author PC
 */
public class Updatecashier extends javax.swing.JFrame {

    /**
     * Creates new form Updatecashier
     */
    public Updatecashier() {
        initComponents();
       this.setResizable(false);
       this.pack();
      this.setLocationRelativeTo(null);
      this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firn1 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        firn4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        firn5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 392));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firn1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firn1.setForeground(new java.awt.Color(0, 255, 255));
        firn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firn1.setText("Contact Number");
        getContentPane().add(firn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 150, 40));

        password.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 255, 255));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/018-password-1.png"))); // NOI18N
        password.setText("Change Password");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 230, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UPDATE ACCOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 60));
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 280, 40));

        firn4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firn4.setForeground(new java.awt.Color(0, 255, 255));
        firn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firn4.setText("First name");
        getContentPane().add(firn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 40));

        fname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 40));

        firn5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firn5.setForeground(new java.awt.Color(0, 255, 255));
        firn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firn5.setText("Last name");
        getContentPane().add(firn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 100, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/021-undo.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/022-updated_1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 90, 90));

        lname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nm.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        this.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        new changePass().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_passwordMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
                                       
    dbConnect dbc = new dbConnect();

    if (fname.getText().isEmpty() || lname.getText().isEmpty() || cn.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All Fields Are Required");
    } else if (fname.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "First Name is required");
        fname.setText("");
    } else if (lname.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Last Name is required"); // fixed incorrect message
        lname.setText("");
    } else if (cn.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Contact Number is required");
        cn.setText("");
    } else {
        String input = cn.getText();
        if (!input.matches("[0-9]{11}")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits only)");
            cn.setText("");
        } else {
            String sql = "UPDATE tbl_user SET u_fname = '" + fname.getText() +
                    "', u_lname = '" + lname.getText() +
                    "', u_cn = '" + cn.getText() + "' WHERE u_id = '" + Session.getInstance().getUid() + "'";
            dbc.UpdateData(sql);
            JOptionPane.showMessageDialog(null, "Data Updated Successfully!");
            
        }
    }


    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
           Session sess = Session.getInstance();
        fname.setText(""+sess.getFname());
        lname.setText(""+sess.getLname());
        cn.setText(""+sess.getCn());
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updatecashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn;
    private javax.swing.JLabel firn1;
    private javax.swing.JLabel firn4;
    private javax.swing.JLabel firn5;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
